import Head from 'next/head';

import { useRouter } from 'next/router';

import Card from '@/components/card';
import useAuth from '@/hooks/auth.hook';
import { authRoutes } from '@/routes';

const Home = () => {
  const { isLoggedIn } = useAuth();
  const router = useRouter();
  return (
    <>
      {isLoggedIn ? 'IAM LOGGED IN' : 'IAM NOT LOGGED IN'}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Card cardName='Nextjs' currNumber={1} />
      <button onClick={() => router.push(authRoutes.login)}>Login</button>
    </>
  );
};
export default Home;
